# Generated by Django 5.1 on 2024-08-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceembed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceembed',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
